language: cpp
compiler: 
  - g++

os: linux
dist: trusty
sudo: require

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.55-all-dev

script:
- gcc -v && g++ -v && cmake --version
- mkdir build && cd build && cmake .. && make
